### ISSUE TITLE
Generate Python wheels compatible with Mac Apple Silicon M1/M2

### ISSUE THREAD

**Issue by fteicht** [aiplan4eu/up-fast-downward#22]
Mac Apple Silicon M1/M2 processors equip by default the Mac Book computers since 2020. Those processors use the ARM64 architecture for which the default Python interpreter is compiled.

Therefore, up-tamer can only be used on those new Mac computers through Rosetta2 and x86 Python interpreters, which:
1. does not allow the user to benefit from the ARM64 computational power
2. requires the user to install an x86 homebrew and Python interpreter.

Since the ARM64 architecture is the default one on all the Mac Book computers assembled since 2020, it would be nice to provide Python wheels for the ARM64 architecture.

It should not be difficult to build such a wheel in the GitHub actions, since I can build the up-fast-downward wheel on my Mac Book Pro equipped with a Mac Apple Silicon M2 processor, without any issue.

**Comment by roeger** [comment]
@fteicht Thank you very much for the pull request! It is now in the main branch.

**Comment by fteicht** [comment]
> @fteicht Thank you very much for the pull request! It is now in the main branch.

Thanks a lot @roeger for having accepted and merged it!
