### ISSUE TITLE
how to use evaluator?

### ISSUE THREAD

**Issue by narcissusgod** [aiplan4eu/up-fast-downward#25]
Hello, I would like to ask how to use evaluators in up-fastdownward? For example, if I want to execute 
./fast-downward.py domain.pddl task.pddl --evaluator "hff=ff()" --evaluator "hcea=cea()" --search "lazy_greedy([hff, hcea], preferred=[hff, hcea])"
, how should I pass the parameters?

**Comment by narcissusgod** [comment]
![image](https://github.com/user-attachments/assets/acf3eaaf-9dfb-4ae7-9305-50386374033e)
I couldn't find the options for setting the evaluator.

**Comment by roeger** [comment]
There is an example in the [usage examples notebook](https://github.com/aiplan4eu/up-fast-downward/blob/main/notebooks/usage-examples.ipynb). Your example still uses the old configuration format of Fast Downward. With the new one, it should be something like:

```
params = {
    'fast_downward_search_config': 'let(hff, ff(), let(hcea, cea(), lazy_greedy([hff, hcea], preferred=[hff, hcea])))'
}

with OneshotPlanner(name='fast-downward', params=params) as planner:
    result = planner.solve(problem)
    if result.status == up.engines.PlanGenerationResultStatus.SOLVED_SATISFICING:
        print("Found an plan of length:", len(result.plan.actions))

        print(result.plan)
    else:
        print("No plan found.")
```

Does this help?

**Comment by narcissusgod** [comment]
Thank you!
